### PR TITLE
Switch anyOf to oneOf (discriminate union) as expected by JSON specification

### PR DESCRIPTION
**Pull request by mattseddon**
Replaces #39

This PR fixes the union issues shown in the on-hover provider in VS Code.

Background/reasoning for the change can be found at https://github.com/pydantic/pydantic/issues/656. The tl;dr is that `anyOf` does not work well in a JSON schema. This leads to unexpected behaviour in on-hover information provided by the current schema.

### Before

https://github.com/iterative/dvcyaml-schema/assets/37993418/9d5389d6-d64e-41ae-b46b-34a945418fab

### After

https://github.com/iterative/dvcyaml-schema/assets/37993418/3e24f818-eea3-43e6-8dd4-a631695c9ea8

### CODE REVIEW

**Comment by mattseddon** [comment]
This might not be the best approach. Please LMK if you know of a better way around the issue. 🙏🏻

**Review by dberenbaum — APPROVED** [review]
Product-wise LGTM

**Comment by daavoo** [comment]
> The tl;dr is that anyOf does not work well in a JSON schema. This leads to unexpected behaviour in on-hover information provided by the current schema.

@mattseddon is there a case where we still want `anyOf`?? I see that there are some left in the schema.

If not, maybe we can simplify this and apply a simple string replacement when dumping?:

```py
json_str = json.dumps(
    DvcYamlModel.schema_json(), indent=2)
).replace("anyOf", "oneOF")
args.outfile.write(json)
```

**Comment by mattseddon** [comment]
> > The tl;dr is that anyOf does not work well in a JSON schema. This leads to unexpected behaviour in on-hover information provided by the current schema.
> 
> @mattseddon is there a case where we still want `anyOf`?? I see that there are some left in the schema.
> 
> If not, maybe we can simplify this and apply a simple string replacement when dumping?:
> 
> ```python
> json_str = json.dumps(
>     DvcYamlModel.schema_json(), indent=2)
> ).replace("anyOf", "oneOF")
> args.outfile.write(json_str)
> ```

I don't think there is a good reason for keeping them at all. I'd be happy to switch to that approach. Just felt like the change that I made was a bit less of a hack but only by a tiny amount.

**Comment by daavoo** [comment]
> I don't think there is a good reason for keeping them at all. I'd be happy to switch to that approach. Just felt like the change that I made was a bit less of a hack but only by a tiny amount.

Yeah, I think it would be ok, we can just put a comment in the replace line. At least we would not be relying on pydantic internals that might break

**Comment by mattseddon** [comment]
> Yeah, I think it would be ok, we can just put a comment in the replace line. At least we would not be relying on pydantic internals that might break

Made the change. LMK if you need anything else 🙏🏻.

**Review by daavoo — APPROVED** [review]
Didn't test in the extension but code change lgtm

**Pull request merged**
